[package]
name = "ccupdater_cli_rs"
version = "0.1.0"
authors = ["CCDirectLink Contributors"]
license = "MIT"

[dependencies]
clap = { version = "3.0.0-beta.1", git = "https://github.com/clap-rs/clap.git"}
